import { DRUID_TALENT_VALUES, PRIEST_TALENT_VALUES } from './data.js';

const priestValues = PRIEST_TALENT_VALUES;

export const TALENT_TREES = {
  priest: [
    { id: 'conservation-of-faith', row: 1, maxRank: 2, name: 'Conservation of Faith', description: `Increase the Priest’s Mana regeneration by ${priestValues.conservationOfFaith.manaRegenPerRank * 100}% / ${priestValues.conservationOfFaith.manaRegenPerRank * 200}%.` },
    { id: 'binding-light', row: 1, maxRank: 2, name: 'Binding Light', description: `Flash Heal also heals the lowest-health eligible other living ally for ${priestValues.bindingLight.effectiveHealRatioByRank[1] * 100}% / ${priestValues.bindingLight.effectiveHealRatioByRank[2] * 100}% of the primary target’s effective heal.` },
    { id: 'early-mercy', row: 1, maxRank: 2, name: 'Early Mercy', description: `Greater Heal delivers ${priestValues.earlyMercy.provisionalRatioByRank[1] * 100}% / ${priestValues.earlyMercy.provisionalRatioByRank[2] * 100}% of its heal halfway through the cast, then the remainder at completion. Mana is charged once when casting starts; interrupting before halfway gives no heal, while interrupting afterward keeps the provisional heal. Mana is not refunded.` },
    { id: 'post-haste', row: 2, maxRank: 2, name: 'Post-Haste', description: `Each Flash Heal grants one stack, up to 1 / 2. The next Greater Heal or Prayer of Healing consumes one stack, reducing its cast time and Mana cost by ${priestValues.postHaste.castAndManaReduction * 100}%.` },
    { id: 'focused-penance', row: 2, maxRank: 2, name: 'Focused Penance', description: `Subtract ${priestValues.focusedPenance.cooldownReductionPerRank}s / ${priestValues.focusedPenance.cooldownReductionPerRank * 2}s from Penance’s current base cooldown.` },
    { id: 'lingering-prayer', row: 2, name: 'Lingering Prayer', description: `After Prayer of Healing, each target still below ${priestValues.lingeringPrayer.threshold * 100}% Health receives a ${priestValues.lingeringPrayer.duration}s HoT worth ${priestValues.lingeringPrayer.ratio * 100}% of that target’s direct heal (${priestValues.lingeringPrayer.interval}s ticks).` },
    { id: 'fourfold-penance', row: 3, name: 'Fourfold Penance', description: `Penance fires ${priestValues.fourfoldPenance.mainBolts} main bolts at its target and one additional bolt that heals the lowest-health other living ally; all four bolts use the normal Penance healing or damage rules.` },
    { id: 'echo-of-grace', row: 3, name: 'Echo of Grace', description: `Flash Heal and Greater Heal also heal the lowest-health other wounded ally for ${priestValues.echoOfGrace.ratio * 100}% of their direct heal.` },
    { id: 'light-unspent', row: 3, name: 'Light Unspent', description: `Prayer of Healing shares ${priestValues.lightUnspent.overhealRatio * 100}% of its direct overhealing evenly among allies still injured after its direct heals.` },
    { id: 'twin-penance', row: 4, name: 'Twin Penance', description: `Penance stores ${priestValues.twinPenance.charges} charges. Each charge recharges in its current cooldown time; recharges occur one at a time.` },
    { id: 'sanctuary', row: 4, name: 'Sanctuary', description: `Instantly reduces all party damage taken by ${priestValues.sanctuary.reduction * 100}% for ${priestValues.sanctuary.duration}s. ${priestValues.sanctuary.cooldown}s cooldown.` },
    { id: 'divine-fervor', row: 4, name: 'Divine Fervor', description: `Instantly grants the Priest ${priestValues.divineFervor.speed * 100}% Haste and reduces all spell Mana costs by ${priestValues.divineFervor.manaReduction * 100}% for ${priestValues.divineFervor.duration}s. ${priestValues.divineFervor.cooldown}s cooldown.` },
  ],
  druid: [
    { id: 'natural-regeneration', row: 1, maxRank: 2, name: 'Natural Regeneration', description: `Increase all Druid Mana regeneration by ${DRUID_TALENT_VALUES.naturalRegeneration.manaRegenPerRank * 100}% / ${DRUID_TALENT_VALUES.naturalRegeneration.manaRegenPerRank * 200}%, including regeneration from gear.` },
    { id: 'empowered-rejuvenation', row: 1, maxRank: 2, name: 'Empowered Rejuvenation', description: 'Increase each Rejuvenation tick and its total healing by 10% / 20%.' },
    { id: 'nourishing-touch', row: 1, maxRank: 2, name: 'Nourishing Touch', description: 'Each completed 2-second Nourish cast adds 1 / 2 normal-strength ticks to each active Rejuvenation, Regrowth, Wild Growth, and triggered Cenarion Ward HoT on its target. Nourish does not extend itself; extensions have no cap.' },
    { id: 'passing-bloom', row: 2, name: 'Passing Bloom', description: 'Replacing Regrowth moves its old HoT to the lowest-health-percentage wounded living ally without Regrowth, refreshed to 9 seconds (3 normal ticks). If none qualifies, the old HoT ends.' },
    { id: 'cenarion-ward', row: 2, maxRank: 2, name: 'Cenarion Ward', description: 'Grant 1 / 2 charges of Cenarion Ward. Each costs 45 Mana and recharges in 30 seconds. The ward lasts 20 seconds and triggers at or below 50% Health, healing 30 each second for 6 seconds (180 total). Recasting replaces an armed Ward; triggered HoTs coexist.' },
    { id: 'abundant-nourishment', row: 2, maxRank: 2, name: 'Abundant Nourishment', description: `Add ${DRUID_TALENT_VALUES.abundantNourishment.healingPerHotPerRank} / ${DRUID_TALENT_VALUES.abundantNourishment.healingPerHotPerRank * 2} healing to Nourish per active Rejuvenation, Regrowth, or Wild Growth type. Ward does not count. Nourish ticks each second for 4 seconds; recasting adds to its unspent pool and refreshes the 4-second window.` },
    { id: 'blooming-swiftmend', row: 3, name: 'Blooming Swiftmend', description: 'Swiftmend also heals the two most injured other living allies for 30% of its primary raw heal each. Its required HoT is preserved.' },
    { id: 'overgrowth', row: 3, name: 'Overgrowth', description: 'Wild Growth costs 20% less Mana and remains castable during cooldown with a 1-second base cast, carrying remaining healing. When a tick leaves an ally above 90% Health, transfer half its remaining Wild Growth healing to the lowest-health-percentage wounded eligible ally.' },
    { id: 'living-rejuvenation', row: 3, name: 'Living Rejuvenation', description: 'Rejuvenation ticks 20% faster below 50% Health. At full Health, its next tick moves with its remaining healing to the lowest-health-percentage wounded living ally with room for Rejuvenation.' },
    { id: 'genesis', row: 4, name: 'Genesis', description: 'Restore active Rejuvenation, Regrowth, and Wild Growth HoTs to full duration, then make them tick 15% faster for 8 seconds. Nourish pools and Ward HoTs are excluded. 60-second cooldown.' },
    { id: 'twin-rejuvenation', row: 4, name: 'Twin Rejuvenation', description: 'Allow two independent Rejuvenation HoTs on one ally; recasting replaces the one with the shortest remaining duration.' },
    { id: 'tranquility', row: 4, name: 'Tranquility', description: 'Channel for 5 seconds, healing every living ally for 30 each second (150 per ally). Costs 100 Mana; 60-second cooldown.' },
  ],
};
